### ISSUE TITLE
No such file or directory: '/sys/class/drm/card0/device/power_method'

### ISSUE THREAD

**Issue by Nowaker** [StuntsPT/Radeon-tray#9]
It appears the program tries to use `card0` while my AMD card is under `card1`. `card0` is an integrated Intel GPU.

```
nowaker@nwkr-desktop ~ % cat /sys/class/drm/card1/device/power_method 
profile
```

Program output:

```
nowaker@nwkr-desktop ~ % radeontray
Traceback (most recent call last):
  File "/usr/bin/radeontray", line 11, in <module>
    load_entry_point('Radeon-tray==1.1.dev0', 'console_scripts', 'radeontray')()
  File "/usr/lib/python3.6/site-packages/radeontray/mainfunctions.py", line 20, in client
    client_main()
  File "/usr/lib/python3.6/site-packages/radeontray/radeontrayclient.py", line 251, in client_main
    main()
  File "/usr/lib/python3.6/site-packages/radeontray/radeontrayclient.py", line 216, in main
    init_method, init_profile = power_status_get(client=SOCKET).split(",")
  File "/usr/lib/python3.6/site-packages/radeontray/utils.py", line 108, in power_status_get
    with open("/sys/class/drm/card"+str(num)+"/device/power_method","r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/power_method'
```

**Comment by StuntsPT** [comment]
Thanks for reporting.
This program is from another "era", when radeon cards did not come coupled with intel IGPs.
I haven't touched this code in years, since my last radeon died on me, but I will take a look.
If it is a simple fix I'll do it.
At the very least, I can tell you what needs to be changed, and if you are versed in python you can fix it based on that...

**Comment by StuntsPT** [comment]
I have pushed a potential fix to a new branch:
https://github.com/StuntsPT/Radeon-tray/tree/DMP.intel.fix
Please let me know if it works.
Also note that I do not have a Radeon/AMD card available, so this fix was performed without any kind of testing.

**Comment by StuntsPT** [comment]
I have just tested this branch on a friend's laptop with a radeon card and it's working as intended.
Could you please confirm?
Thanks.

**Comment by Nowaker** [comment]
Hey, I'll check this weekend. Thanks!

**Comment by Nowaker** [comment]
I actually checked it right now. It doesn't work yet.

```
nowaker@nwkr-desktop ~ % radeontray                                              
Traceback (most recent call last):
  File "/usr/bin/radeontray", line 11, in <module>
    load_entry_point('Radeon-tray==1.1.dev0', 'console_scripts', 'radeontray')()
  File "/usr/lib/python3.6/site-packages/radeontray/mainfunctions.py", line 20, in client
    client_main()
  File "/usr/lib/python3.6/site-packages/radeontray/radeontrayclient.py", line 196, in client_main
    main()
  File "/usr/lib/python3.6/site-packages/radeontray/radeontrayclient.py", line 164, in main
    init_method, init_state = power_status_get(client=SOCKET).split(",")
  File "/usr/lib/python3.6/site-packages/radeontray/utils.py", line 145, in power_status_get
    with open("/sys/class/drm/card"+str(num)+"/device/power_method","r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/power_method'
```

It needs to **skip** any operations on `card0` (possibly by checking for existence of /sys/class/drm/card0/device/power_method rather than /sys/class/drm/card0 [here](https://github.com/StuntsPT/Radeon-tray/commit/515e4aa08fe41153bf22f33589188b6525b8aee1#diff-65e05ee16f56345d7f7eccf6b0689391R46)) or handle exceptions when trying to read `power_method` file that doesn't exist.

**Comment by StuntsPT** [comment]
Ah!
I'll have to add a name check or something. In your case, card0 is an intel card. I was assuming (for some stupid reason) that in your case `card0` would not exist.
I think I know what to do now. Just need some time.

**Comment by StuntsPT** [comment]
Ok, please try the latest version of this branch.
I have not way to test it but I suppose adding the full path as you suggested should do the trick, as IIRC only radeon cards will have that full path.

**Comment by Nowaker** [comment]
Thanks for the fix. I have a sad news (for myself), though. I can't test it. I removed my Radeon card died just today. But - the code change looks good and I'm sure it would work now, so I suggest you merge it and release a new version. Many thanks!

**Comment by StuntsPT** [comment]
Ok, so I just got my hands on a laptop with an intel and a Radeon card, and running the new branch there results in... nothing.
The program does not run and does not throw any errors. If I had more time I could have figured it out, but as it was I couldn't.
So until someone with combo like yours is able to help me further debug the issue this will unfortunately remain an unmerged branch..

**Comment by TheSecureTux** [comment]
I am having this issue too and I'm actually not sure if the branch was working or not because what appears to be giving me grief now is pyqt4/5 (I think):

                                                                                                                                             INT ✘  at 22:31:37 
```
❯ radeontray
Traceback (most recent call last):
  File "/usr/bin/radeontray", line 33, in <module>
    sys.exit(load_entry_point('Radeon-tray==1.1.dev0', 'console_scripts', 'radeontray')())
  File "/usr/bin/radeontray", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/Radeon_tray-1.1.dev0-py3.8.egg/radeontray/mainfunctions.py", line 7, in <module>
    from .radeontrayclient import client_main
  File "/usr/lib/python3.8/site-packages/Radeon_tray-1.1.dev0-py3.8.egg/radeontray/radeontrayclient.py", line 25, in <module>
    from PyQt4 import QtGui, QtCore
  File "/home/tux/.local/lib/python3.8/site-packages/PyQt4/__init__.py", line 12, in <module>
    _qt_backport.emulate(emulator, wrapper)
  File "/home/tux/.local/lib/python3.8/site-packages/qt_backport/__init__.py", line 75, in emulate
    emulation_dispatcher[(emulator, wrapper)](emulator_module)
  File "/home/tux/.local/lib/python3.8/site-packages/qt_backport/__init__.py", line 58, in _emulate_pyqt4_with_pyqt5
    _create_base_qt4_emulator_with_pyqt5(emulator_module)
  File "/home/tux/.local/lib/python3.8/site-packages/qt_backport/__init__.py", line 36, in _create_base_qt4_emulator_with_pyqt5
    from . import qt5_backport as _qt5_backport
  File "/home/tux/.local/lib/python3.8/site-packages/qt_backport/qt5_backport.py", line 296
    cls.light = lambda(self): self.lighter() #Qt4.2 -> Qt4.3
                      ^
SyntaxError: invalid syntax
```
I was trying and messed a bit with the code to see if I could get it to work ( bur my python skills are rather limited) and I am not sure aboyut the pyqt4/5/backport stuff. ¯\_(ツ)_/¯

**Comment by StuntsPT** [comment]
Hi @Nowaker and @TheSecureTux .
Radeon tray was developed when radeon cards did not have dynamic power management on GNU/Linux based OSes. This small applet was used to manually control it (and boy, did that work!).
However, as time went by AMD has invested a lot in their OSS drivers, and dynamic power management is now a very sane default. As such I really don't see how this program can be useful any longer and will be archiving it.

Thank you for reminding me this was still online. =-)
